### PR TITLE
add lang es to config yaml

### PR DESCRIPTION
**Pull request by avallecam**
after merging, lets check if we need to change the sandpaper line as in line https://github.com/avallecam/workbench-spanish/blob/main/config.yaml#L78

### CODE REVIEW

**Comment by Bisaloo** [comment]
We solved the sandpaper error. It's not a different problem. With matrixStats.

**Comment by Bisaloo** [comment]
I think matrixStats needs to be updated to a more modern version in `renv.lock` as well. That version is so old that it's not compatible with our compiler.

**Comment by avallecam** [comment]
Thank you, Hugo.

Yes, indeed. It was due to the version included in the `renv.lock`. Yesterday we identified that {MatrixStats} was part of {EpiEstim} dependency tree (within {coarseDataTools}).

We solved it in https://github.com/Joskerus/Nuevoformato/commit/d07d3517bf4e80bb894f2019de8f09ea908d6959 and https://github.com/Joskerus/Nuevoformato/commit/421eda63a03ff1dfec6905ba74e8293f8f41fd2d by replacing the `renv.lock` with the one I generated in the workbench-spanish repo.

I replaced the explicit installation from r-universe to CRAN with sandpaper::pin_version(), removing the explicit reference to all the dependency tree in the `renv.lock` file, leaving to the GitHub action to install them, see this commit https://github.com/avallecam/workbench-spanish/commit/84081595ccfd0878ef4112f8eb7bf0866d59b472

Then I tried the same for {rstan} which also generated a similar error in previous workflows, so added a pin_version of it too in a later commit, and it worked fine.

This solution is still under observation.

**Comment by avallecam** [comment]
I'll close this PR since the change proposed here was added directly to main in https://github.com/Joskerus/Nuevoformato/commit/ed76d80f5e8b81023937e9fb63e3d44c209f0df9

We could cite the comments on matrixStats in a separate issue.

**Pull request closed without merging**
